version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: notesapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: notesapp_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
